name: Blue/Green - Deploy ATS Server to GKE

on:
  push:
    branches: [main]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }} # REPOSITORY/APP_NAME
  CLUSTER: ${{ secrets.CLUSTER }}
  REGION: ${{ secrets.REGION }}
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
  build-deploy:
    name: Build and Push Image to GCR
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install gcloud cli
        id: setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: generate image tag
        id: tag
        run: |
          echo "TAG=$(bash ./scripts/tag.sh)" >> $GITHUB_ENV

      - name: run all test
        run: echo "Testing app..."

      - name: detect secrets
        run: echo "TruffleHog OSS to detect secrets"

      - name: build and push the docker image
        env:
          IMAGE_TAG: ${{ env.TAG }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build \
          -t $REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest \
          -t $REGISTRY/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG \
          .
          docker push $REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest
          docker push $REGISTRY/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG

      - name: deploy to gke
        env:
          IMAGE: $REGISTRY/$PROJECT_ID/$IMAGE_NAME:${{ env.TAG }}
        run: |
          gcloud container clusters get-credentials $CLUSTER --region $REGION
          ./scripts/deploy.sh ${{ env.APP_NAME }} ${{ env.TAG }} ${{ env.IMAGE }} ./k8s/deploy.tmpl
